// <auto-generated />
using System;
using FinanceTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614160422_AddCategories")]
    partial class AddCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceTracker.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("categories", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-000000000001"),
                            Color = "#22c55e",
                            Icon = "shopping-cart",
                            IsSystem = true,
                            Name = "Продукты"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-000000000002"),
                            Color = "#f97316",
                            Icon = "utensils",
                            IsSystem = true,
                            Name = "Кафе и рестораны"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-000000000003"),
                            Color = "#3b82f6",
                            Icon = "car",
                            IsSystem = true,
                            Name = "Транспорт"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-000000000004"),
                            Color = "#8b5cf6",
                            Icon = "house",
                            IsSystem = true,
                            Name = "Жильё"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-000000000005"),
                            Color = "#ef4444",
                            Icon = "heart-pulse",
                            IsSystem = true,
                            Name = "Здоровье"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-000000000006"),
                            Color = "#ec4899",
                            Icon = "gamepad-2",
                            IsSystem = true,
                            Name = "Развлечения"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-000000000007"),
                            Color = "#14b8a6",
                            Icon = "shirt",
                            IsSystem = true,
                            Name = "Одежда"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-000000000008"),
                            Color = "#06b6d4",
                            Icon = "wifi",
                            IsSystem = true,
                            Name = "Связь и интернет"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-000000000009"),
                            Color = "#eab308",
                            Icon = "graduation-cap",
                            IsSystem = true,
                            Name = "Образование"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-00000000000a"),
                            Color = "#d946ef",
                            Icon = "gift",
                            IsSystem = true,
                            Name = "Подарки"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-00000000000b"),
                            Color = "#10b981",
                            Icon = "wallet",
                            IsSystem = true,
                            Name = "Зарплата"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-00000000000c"),
                            Color = "#64748b",
                            Icon = "ellipsis",
                            IsSystem = true,
                            Name = "Прочее"
                        });
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("RUB");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("user_profiles", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
