// <auto-generated />
using System;
using FinanceTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceTracker.Domain.Entities.Accrual", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("ExchangeRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IncludeInStats")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ReceiptId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ReceiptId")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("accruals", "public");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.AccrualTag", b =>
                {
                    b.Property<Guid>("AccrualId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("AccrualId", "Tag");

                    b.HasIndex("Tag");

                    b.ToTable("accrual_tags", "public");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("categories", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-000000000001"),
                            Color = "#22c55e",
                            Icon = "shopping-cart",
                            IsSystem = true,
                            Name = "Продукты"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-000000000002"),
                            Color = "#f97316",
                            Icon = "utensils",
                            IsSystem = true,
                            Name = "Кафе и рестораны"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-000000000003"),
                            Color = "#3b82f6",
                            Icon = "car",
                            IsSystem = true,
                            Name = "Транспорт"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-000000000004"),
                            Color = "#8b5cf6",
                            Icon = "house",
                            IsSystem = true,
                            Name = "Жильё"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-000000000005"),
                            Color = "#ef4444",
                            Icon = "heart-pulse",
                            IsSystem = true,
                            Name = "Здоровье"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-000000000006"),
                            Color = "#ec4899",
                            Icon = "gamepad-2",
                            IsSystem = true,
                            Name = "Развлечения"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-000000000007"),
                            Color = "#14b8a6",
                            Icon = "shirt",
                            IsSystem = true,
                            Name = "Одежда"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-000000000008"),
                            Color = "#06b6d4",
                            Icon = "wifi",
                            IsSystem = true,
                            Name = "Связь и интернет"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-000000000009"),
                            Color = "#eab308",
                            Icon = "graduation-cap",
                            IsSystem = true,
                            Name = "Образование"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-00000000000a"),
                            Color = "#d946ef",
                            Icon = "gift",
                            IsSystem = true,
                            Name = "Подарки"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-00000000000b"),
                            Color = "#10b981",
                            Icon = "wallet",
                            IsSystem = true,
                            Name = "Зарплата"
                        },
                        new
                        {
                            Id = new Guid("a1c00000-0000-7000-8000-00000000000c"),
                            Color = "#64748b",
                            Icon = "ellipsis",
                            IsSystem = true,
                            Name = "Прочее"
                        });
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.ChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValuesAfter")
                        .HasColumnType("text");

                    b.Property<string>("ValuesBefore")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("change_logs", "public");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RequestMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Key", "UserId", "RequestPath")
                        .IsUnique();

                    b.ToTable("idempotency_records", "public");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.MonthlyBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("LimitAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "CategoryId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("monthly_budgets", "public");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("AmountInKopecks")
                        .HasColumnType("bigint");

                    b.Property<string>("Cashier")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long?>("FD")
                        .HasColumnType("bigint");

                    b.Property<string>("FN")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("FPD")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("FetchAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("FetchStatus")
                        .HasColumnType("integer");

                    b.Property<string>("INN")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTimeOffset?>("NextFetchAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Organization")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("QrRaw")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RawMetadata")
                        .HasColumnType("text");

                    b.Property<int?>("ShiftNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("TaxationType")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("FetchStatus", "NextFetchAt");

                    b.ToTable("receipts", "public");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.ReceiptItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Sum")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.ToTable("receipt_items", "public");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("RUB");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("user_profiles", "public");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.Accrual", b =>
                {
                    b.HasOne("FinanceTracker.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinanceTracker.Domain.Entities.Receipt", "Receipt")
                        .WithOne()
                        .HasForeignKey("FinanceTracker.Domain.Entities.Accrual", "ReceiptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.AccrualTag", b =>
                {
                    b.HasOne("FinanceTracker.Domain.Entities.Accrual", null)
                        .WithMany("Tags")
                        .HasForeignKey("AccrualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.MonthlyBudget", b =>
                {
                    b.HasOne("FinanceTracker.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.ReceiptItem", b =>
                {
                    b.HasOne("FinanceTracker.Domain.Entities.Receipt", null)
                        .WithMany("Items")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.Accrual", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.Receipt", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
